[project]
name = "redis_python"
version = "0.1.2"
description = "My small supply_chain simulator"
requires-python = ">=3.8"
license="bsd-3"

[build-system]
requires = ["uv_build >= 0.8.17, <0.9.0"]
build-backend = "uv_build"
